<article class="parcours-item" id="phd">
    <h2>PhD in Physics and Chemistry of Materials</h2>
    <p class="parcours-meta">
        <strong>Topic:</strong> Electronic correlations of acenes towards the large size limit: a Quantum Monte Carlo study <br>
        <strong>Laboratory:</strong> Institute of Mineralogy, Materials Physics and Cosmochemistry (IMPMC), Paris | 2012 - 2016
    </p>
    
    <p>
        Under the supervision of Prof. Michele Casula and Prof. Francesco Mauri, my PhD research focused on predicting the electronic properties of molecules—acenes—which are precursors to graphene nanoribbons.
    </p>
    <p>
        The objective was to better understand, through numerical simulations, the quantum behaviors that could lead to future applications in spintronics or energy storage.
    </p>
    <p>
        This research work and the high standards of my mentors allowed me to develop a set of fundamental skills:
    </p>
    <ul>
        <li><strong>Mastery of the modeling lifecycle:</strong> Conceptualizing a complex physical problem, implementing models, critically analyzing results, and comparing them with the state-of-the-art.</li>
        <li><strong>Analysis and interpretation of large volumes of data:</strong> Processing and extracting value from massive datasets generated by numerical simulations.</li>
        <li><strong>Technical communication:</strong> Synthesizing and disseminating results, writing articles for specialized journals.</li>
    </ul>

    <details>
        <summary>Additional details (thesis, publications...)</summary>
        
        <div class="details-content">
    
            <p><strong>Thesis:</strong> <a href="https://theses.fr/2016PA066143" target="_blank" rel="noopener noreferrer">Consult my thesis manuscript on theses.fr</a></p>
            
            <h4>Publications</h4>
            <ol class="publications-list">
                <li>
                    N. Dupuy and M. Casula, 
                    <a href="https://pubs.aip.org/aip/jcp/article-abstract/148/13/134112/76053/Fate-of-the-open-shell-singlet-ground-state-in-the?redirectedFrom=fulltext" target="_blank" rel="noopener noreferrer">“Fate of the open-shell singlet ground state in the experimentally accessible acenes: A quantum Monte Carlo study”</a>,
                    <em>The Journal of Chemical Physics</em> <strong>148</strong>, 134112 (2018).
                </li>
                <li>
                    N. Dupuy, S. Bouaouli, F. Mauri, S. Sorella, and M. Casula, 
                    <a href="https://pubs.aip.org/aip/jcp/article-abstract/142/21/214109/966760/Vertical-and-adiabatic-excitations-in-anthracene?redirectedFrom=fulltext" target="_blank" rel="noopener noreferrer">“Vertical and adiabatic excitations in anthracene from quantum Monte Carlo...”</a>, 
                    <em>J. Chem. Phys.</em> <strong>142</strong>, 214109 (2015).
                </li>
            </ol>
            
            <h4>Anecdotes</h4>
            <div class="anecdote-item">
                <p>“I am proud to be the first in my family to obtain a doctorate, but I cherish even more the qualities passed down by my family, including the humor of my late grandfather, who loved to remind me: 'I have diplomas too! I got my primary school certificate at 14!'”</p>
            </div>
            <div class="anecdote-item">
                <p>“I obtained my PhD at 36. For a long time, I saw private tutoring as my lifelong profession, but the flexibility of this activity allowed me to explore many fields as an auditing student and to stay connected to the academic world.”</p>
            </div>
            
        </div>
    </details>
</article>