<?php

$anecdotes_neuro = [
    "The brain's sense of priorities. At the Big Data convention in Paris. After a few hours, the ambient noise and the concentration required for social interactions had drained my battery quite a bit. An engaging person at a booth is presenting their company's latest project, and I'm listening intently... focused on the details... but suddenly, she stops, \"Wait... Nicolas?\". It still took me another moment to recognize my friend! If I run into you in an unusual context, please don't be offended; the risk that I genuinely won't recognize you exists!",

    "The ability of autistic people to concentrate deeply is well known. This was the case on the day of an English exam in my early years of study. As usual, I was about twenty minutes early, and as often happens, I seemed to be walking in circles when, in my head, imperceptibly to those who don't know me, I was reviewing everything while walking. I walk past a girl sitting on the stairs several times, greet her politely the first time, then pass by again and again, before, once more, realizing I was walking past a friend, and finally stopping to join her. Here too, once again, you should know that when I'm thinking, I might not notice that you exist!",
    
    "I often appear physically rigid, and this is a trait shared with many autistic people. More generally, it's a difference in body language traits; where most people are more mobile, naturally, in their body movements when communicating, also with rich facial expressions, for us, our nature is to be still. It's quite difficult to pretend not to be autistic (this is called masking) and to make sure to blink often enough, to frown a little from time to time, to smile appropriately and at the right moment... However, what often happens in video calls is that the person I'm talking to thinks my screen has frozen when I'm listening intently!",

    "When an autistic person thinks differently, it happens at a fundamental level. Even for a simple greeting, sometimes I have to think... <<Okay, I'm seeing this person for the first time today, I greet them... how... option 1: shake hands, it's back despite covid, but there's still option 2, bumping fists or elbows, option 3: 'la bise' (the cheek kiss), but be careful at work... but-- what the heck? --it's my girlfriend!>> (it was...)",

    "<strong>To disclose or not to disclose?</strong> <p>For an autistic person, the best strategy is often not to talk about it, as few people understand what one is trying to explain. To illustrate what 'seeing things differently' means, let's use an analogy with colors.</p><p>Imagine that, like the 99% of non-autistic people, you perfectly distinguish green from blue, but I cannot see that difference. It's troublesome. To adapt, we develop tricks and rely on experience to compensate.</p><p>But also imagine that I can see nuances between red and violet, and you cannot. A nuance that only 1% of the population, autistic people, can perceive. Society, built by the majority, has organized itself in such a way that this nuance is irrelevant.</p><p>So, I can either spend my time hiding that I am not quite like you, or we can work with this difference, to work better together, and better appreciate one another.</p>"
];