<?php

$anecdotes_neuro = [
    "Le sens des priorités du cerveau. Au Salon du Big Data à Paris. Après quelques heures, le bruit ambiant et les efforts de concentration pour les interactions sociales ont bien entamé ma batterie. Une personne passionnante me présente le dernier projet de sa société à un stand, et je l'écoute attentivement... attentif aux détails... mais subitement, elle s'interrompt, \"Attends... Nicolas ?\". Il m'a fallu encore un moment avant de reconnaître mon ami! Si je vous croise dans un contexte inhabituel, ne vous vexez pas, le risque que je ne vous reconnaisse (sincèrement) pas existe!",

    "La capacité des personnes autistes à se concentrer profondément est très connue. C'était le cas le jour d'un examen d'anglais de mes premières années d'études. Comme à mon habitude, j'avais une vingtaine de minutes d'avance, et comme souvent, j'avais l'air de tourner en rond quand, dans ma tête, imperceptible pour qui ne me connais pas, je révisais tout en marchant. Je passe plusieurs fois devant une fille assise dans l'escalier, la salue poliment la première fois, puis passe et repasse, avant, encore une fois, de réaliser que je passais devant une amie, et enfin m'arrête pour la rejoindre. Ici aussi, encore une fois, il faut savoir que lorsque je réfléchis, je risque de ne pas m'apercevoir que vous existez!",
    
    "J'ai souvent l'air (physiquement) rigide, et c'est un trait partagé avec de nombreux autistes. Plus généralement, il s'agit d'une différence dans les traits d'expression corporelle, là où la majorité des gens est plus mobile, naturellement, dans le mouvement du corps quand vous communiquez, avec aussi des expressions riches au niveau du visage, pour nous, notre nature est d'être immobiles. C'est assez difficiles de faire semblant de ne pas être autiste (on parle de camouflage) et de veiller à avoir les yeux qui clignent assez souvent, à froncer un peu les sourcils de temps en temps, de sourire à-propos et au bon moment... Par contre, ce qu'il se passe souvent dans les visios, c'est d'avoir notre interlocuteur qui pense que l'écran a freezé quand nous l'écoutons attentivement!",
    
    "Quand un autiste pense différement, ça se joue à un niveau fondamental. Même pour un simple salut, parfois, il me faut penser... 'Donc, je croise cette personne pour la première fois aujourd'hui, je la salue... comment... option 1: serrer la main, malgré le covid, ça a repris, mais il reste l'option 2, se choquer les poings ou les coudes, option 3: la bise, mais faire attention au travail, mais MERcredi... mais c'est mon amoureuse!' (c'était...)",

    "<strong>En parler ou non ?</strong> <p>C'est souvent la meilleure stratégie pour un autiste : ne pas en parler, car peu de personnes comprennent ce que l'on cherche à expliquer. Pour illustrer ce que \"voir les choses différemment\" signifie, utilisons une analogie avec les couleurs.</p><p>Imaginons que, comme les 99% des gens non autistes, vous distinguiez parfaitement le vert du bleu, mais moi, je ne vois pas cette différence. C'est embêtant. Pour nous adapter, nous développons des astuces et faisons appel à l'expérience pour compenser.</p><p>Mais imaginez aussi que moi, je puisse voir des nuances entre le rouge et le violet, et vous non. Une nuance que seul 1% de la population, les autistes, perçoit. La société, construite par la majorité, s'est organisée de telle sorte que cette nuance soit sans importance.</p><p>Je peux alors, soit passer mon temps à cacher que je ne suis pas tout à fait comme vous, ou alors nous pouvons faire avec cette différence, pour mieux travailler, et mieux nous apprécier.</p>"
];